// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDykUFkqwDg-kZvrfRs4e44n1k-RscWH20',
    appId: '1:103597176816:web:b2d5a26dce9f1da9328f35',
    messagingSenderId: '103597176816',
    projectId: 'descartetest',
    authDomain: 'descartetest.firebaseapp.com',
    storageBucket: 'descartetest.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1RXFqO-iyFKmBFUgvKgqIaf8RhnQ8SVw',
    appId: '1:103597176816:android:d98f59206cbbfc67328f35',
    messagingSenderId: '103597176816',
    projectId: 'descartetest',
    storageBucket: 'descartetest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOHZ14YwM8ymG0xpoaUXMVpKo62c8LyWY',
    appId: '1:103597176816:ios:3e83d9d2de788fbc328f35',
    messagingSenderId: '103597176816',
    projectId: 'descartetest',
    storageBucket: 'descartetest.appspot.com',
    iosBundleId: 'com.example.decarteBem',
  );
}
